language: node_js
node_js:
- 8.12.0
notifications:
  email:
    on_success: always
install: true # this skips running npm install
deploy:
  - provider: heroku
    api_key: $HEROKU_TOKEN
    app: rapid-build-io-staging
    on:
      tags: true